# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('account_created', 'Compte cree'), ('signalement_received', 'Signalement recu'), ('signalement_validated', 'Signalement valide'), ('signalement_in_progress', 'Signalement en cours'), ('signalement_resolved', 'Signalement resolu'), ('signalement_rejected', 'Signalement rejete'), ('critical_case', 'Cas critique'), ('report_available', 'Rapport disponible'), ('risk_zone', 'Zone a risque'), ('official_alert', 'Alerte officielle'), ('education_content', 'Contenu educatif'), ('ai_inconsistency', 'Incoherence IA'), ('system_log', 'Alerte systeme')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
