# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('rain', 'Alerte pluie'), ('flood', 'Alerte inondation'), ('pollution', 'Alerte pollution'), ('erosion', 'Alerte erosion'), ('sanitation', 'Alerte salubrite'), ('cleanup', 'Campagne de nettoyage')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('watch', 'Surveillance'), ('warning', 'Alerte'), ('critical', 'Critique')], db_index=True, default='info', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_official', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.commune')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'severity'], name='alerts_offi_is_acti_ab96de_idx'), models.Index(fields=['province', 'commune', 'is_active'], name='alerts_offi_provinc_531ec5_idx')],
            },
        ),
    ]
