# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_detected', models.CharField(max_length=120)),
                ('gravity', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('recommendation', models.TextField()),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('coherence', models.CharField(default='moyenne', max_length=40)),
                ('intervention_type', models.CharField(blank=True, max_length=120)),
                ('priority_level', models.CharField(blank=True, max_length=80)),
                ('recommended_delay', models.CharField(blank=True, max_length=80)),
                ('suggested_team', models.CharField(blank=True, max_length=120)),
                ('duplicate_probability', models.PositiveSmallIntegerField(default=0)),
                ('fraud_flags', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
