# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(default='leaf', max_length=48)),
                ('color', models.CharField(default='#15803d', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='signalements/')),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='signalements/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='signalements/after/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('position_source', models.CharField(choices=[('browser', 'GPS navigateur'), ('exif', 'Metadata EXIF'), ('manual', 'Carte manuelle'), ('unknown', 'Inconnue')], default='unknown', max_length=20)),
                ('exif_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('exif_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('exif_taken_at', models.DateTimeField(blank=True, null=True)),
                ('position_discrepancy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_category_label', models.CharField(blank=True, max_length=120)),
                ('gravity', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Eleve'), ('critique', 'Critique')], db_index=True, default='moyen', max_length=20)),
                ('urgency_level', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Valide'), ('en_cours', 'En cours'), ('resolu', 'Resolu'), ('rejete', 'Rejete')], db_index=True, default='en_attente', max_length=20)),
                ('ai_score', models.PositiveSmallIntegerField(default=0)),
                ('eco_score_impact', models.PositiveSmallIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('is_probable_duplicate', models.BooleanField(db_index=True, default=False)),
                ('fraud_flags', models.JSONField(blank=True, default=list)),
                ('authority_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.category')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.commune')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.signalement')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='signalements/resolution/')),
                ('comment', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_proofs', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='signalements.signalement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['status', 'gravity'], name='signalement_status_39a347_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['commune', 'status'], name='signalement_commune_571988_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['latitude', 'longitude'], name='signalement_latitud_3ed5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['created_at', 'category'], name='signalement_created_aebfdc_idx'),
        ),
    ]
