# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('publication_type', models.CharField(choices=[('actualite', 'Actualite'), ('education', 'Education'), ('communique', 'Communique'), ('rapport-public', 'Mise a disposition'), ('campagne', 'Campagne')], db_index=True, max_length=30)),
                ('excerpt', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('scope_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive')], db_index=True, default='published', max_length=20)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.commune')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province')),
            ],
            options={
                'db_table': 'publications_officielles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['publication_type', 'status', 'is_public'], name='publication_publica_29330f_idx'), models.Index(fields=['province', 'commune', 'status'], name='publication_provinc_57f8a5_idx')],
            },
        ),
    ]
