# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_publication_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialpublication",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="publications/videos/"),
        ),
    ]
