# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('conseil', 'Conseil'), ('guide', 'Guide'), ('pdf', 'PDF'), ('video', 'Video'), ('tutoriel', 'Tutoriel'), ('communique', 'Communique'), ('campagne', 'Campagne')], default='article', max_length=20)),
                ('topic', models.CharField(db_index=True, max_length=120)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='education/pdfs/')),
                ('video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive')], db_index=True, default='published', max_length=20)),
                ('is_official', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_education_contents', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.commune')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
