# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalcontent",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="education/videos/"),
        ),
    ]
