# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('report_type', models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('commune', 'Par commune'), ('province', 'Par province'), ('national', 'National'), ('ai', 'Rapport IA')], db_index=True, max_length=20)),
                ('summary', models.TextField()),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('major_incidents', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('chart_payload', models.JSONField(blank=True, default=dict)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
