# Generated by Django 5.2.15 on 2026-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('commune', 'Par commune'), ('province', 'Par province'), ('national', 'National'), ('ai', 'Rapport IA'), ('urgence', 'Urgence'), ('performance', 'Performance'), ('recommandations', 'Recommandations')], db_index=True, max_length=20),
        ),
    ]
