# Generated by Django 5.2.15 on 2026-07-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ecological_score', models.PositiveSmallIntegerField(default=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ecological_score', models.PositiveSmallIntegerField(db_index=True, default=70)),
                ('risk_level', models.CharField(db_index=True, default='modere', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='locations.province')),
            ],
            options={
                'ordering': ['province__name', 'name'],
                'indexes': [models.Index(fields=['province', 'risk_level'], name='locations_c_provinc_28dee8_idx')],
                'constraints': [models.UniqueConstraint(fields=('province', 'name'), name='unique_commune_per_province')],
            },
        ),
    ]
